import { Onest } from "next/font/google";
import "./globals.css";
import Providers from "@/provider/Provider";

const OnestSans = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata = {
  title: "ena-ema-technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${OnestSans.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
